### ISSUE TITLE
The target ROM is a known bad dump

### ISSUE THREAD

**Issue by SatoMew** [JimB16/PokePlat#6]
Xenophobia's dump has an underdumped header ([source](https://datomatic.no-intro.org/?page=show_record&s=28&n=3541)). This repository in its current state is thus not a disassembly of the real American Platinum v1.0 ROM.

As a reminder, there is [an American Platinum v1.1 ROM](https://datomatic.no-intro.org/?page=show_record&s=28&n=4997) which fixed a bug related to the GTS not found in other releases, and [the English European Platinum ROM](https://datomatic.no-intro.org/?page=show_record&s=28&n=3797) which censored the Game Corner using the same edits as the Korean versions of DPPt.

**Comment by JimB16** [comment]
Some time is gone since I last thougt about changing the rom version. I knew that there were others out there, but sticked with this one because it was easier to find or sth like that.
The header should be easy to fix though. Maybe it only needs an update to the README for this since I extract most data out of the baserom.nds that is provided by the user and use that to rebuild a new rom.

Thanks for the reminder.

**Comment by JimB16** [comment]
Changed baserom to the American Platinum v1.1 ROM. Support for v1.0 will come when someone removed all incbins from that one overlay.
